### ISSUE TITLE
Warning: a promise was created in a handler

### ISSUE THREAD

**Issue by maxfriedmann** [v4l3r10/node-cache-manager-mongodb#29]
As soon as I use this package, I get the following warning from bluebird: 

```
Warning: a promise was created in a handler at \project_path\node_modules\rxjs\src\internal\operators\OperatorSubscriber.ts:98:18 but was not returned from it, see http://goo.gl/rRqMUw
    at \project_path\node_modules\cache-manager-mongodb\node_modules\bluebird\js\release\promise.js:484:17
    at processImmediate (node:internal/timers:466:21)
    at process.topLevelDomainCallback (node:domain:161:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
From previous event:
    at Object.complete (\project_path\node_modules\rxjs\src\internal\lastValueFrom.ts:67:11)
    at ConsumerObserver.complete (\project_path\node_modules\rxjs\src\internal\Subscriber.ts:185:25)
    at SafeSubscriber.Subscriber._complete (\project_path\node_modules\rxjs\src\internal\Subscriber.ts:132:24)
    at SafeSubscriber.Subscriber.complete (\project_path\node_modules\rxjs\src\internal\Subscriber.ts:106:12)
    at OperatorSubscriber.Subscriber._complete (\project_path\node_modules\rxjs\src\internal\Subscriber.ts:132:24)
    at OperatorSubscriber.Subscriber.complete (\project_path\node_modules\rxjs\src\internal\Subscriber.ts:106:12)
    at checkComplete (\project_path\node_modules\rxjs\src\internal\operators\mergeInternals.ts:48:18)
    at OperatorSubscriber.onFinalize (\project_path\node_modules\rxjs\src\internal\operators\mergeInternals.ts:125:15)
    at OperatorSubscriber.unsubscribe (\project_path\node_modules\rxjs\src\internal\operators\OperatorSubscriber.ts:109:33)
    at OperatorSubscriber._this._complete (\project_path\node_modules\rxjs\src\internal\operators\OperatorSubscriber.ts:98:18)
    at OperatorSubscriber.Subscriber.complete (\project_path\node_modules\rxjs\src\internal\Subscriber.ts:106:12)
    at OperatorSubscriber.Subscriber._complete (\project_path\node_modules\rxjs\src\internal\Subscriber.ts:132:24)
    at OperatorSubscriber.Subscriber.complete (\project_path\node_modules\rxjs\src\internal\Subscriber.ts:106:12)
    at checkComplete (\project_path\node_modules\rxjs\src\internal\operators\mergeInternals.ts:48:18)
    at OperatorSubscriber.onFinalize (\project_path\node_modules\rxjs\src\internal\operators\mergeInternals.ts:125:15)
    at OperatorSubscriber.unsubscribe (\project_path\node_modules\rxjs\src\internal\operators\OperatorSubscriber.ts:109:33)
    at OperatorSubscriber._this._complete (\project_path\node_modules\rxjs\src\internal\operators\OperatorSubscriber.ts:98:18)
From previous event:
    at lastValueFrom (\project_path\node_modules\rxjs\src\internal\lastValueFrom.ts:56:10)
    at RouterResponseController.transformToResult (\project_path\node_modules\@nestjs\core\router\router-response-controller.js:33:45)
    at \project_path\node_modules\@nestjs\core\router\router-execution-context.js:174:52
    at \project_path\node_modules\@nestjs\core\router\router-execution-context.js:47:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at \project_path\node_modules\@nestjs\core\router\router-proxy.js:9:17
```

Is this a known issue?

My project is using bluebird 3.7.2 (deduped  from another library), node 16.18 LTS and RxJS 7.5.6

**Comment by maxfriedmann** [comment]
wrote my own, nevermind...
